### ISSUE TITLE
"bucket" names both a type and a variable in cuckoopath_move().

### ISSUE THREAD

**Issue by toojays** [efficient/libcuckoo#104]
https://github.com/efficient/libcuckoo/blob/6591795a944fa8c7268848d181ba2852f4a7897f/libcuckoo/cuckoohash_map.hh#L1369

The project I'm using libcuckoo in enables a bunch of compiler warnings including ``-Wshadow``. With GCC 8, we now get this complaint:

```
/home/jscott/src/libcuckoo/libcuckoo/cuckoohash_map.hh:1369:23: warning: declaration of ‘bucket’ shadows a previous local [-Wshadow]
       const size_type bucket = cuckoo_path[0].bucket;
                       ^~~~~~
/home/jscott/src/libcuckoo/libcuckoo/cuckoohash_map.hh:1002:44: note: shadowed declaration is here
   using bucket = typename buckets_t::bucket;
                                            ^
```

Newer GCC (7+) has the more nuanced ``-Wshadow=compatible-local``, which does not produce this warning. That may be a better choice in the long term.

Anyway, we've changed it locally by just renaming ``bucket`` to ``bucket_i`` within ``cuckoopath_move()``. Would you take a PR with a change like this? Is there a better name than ``bucket_i``? ``deepest_bucket`` or something? (I'm not even sure if it's the deepest or the top one TBH.)

**Comment by BurningEnlightenment** [comment]
Btw Visual Studio 2017 produces a similar warning with -W4 enabled IIRC.
