### ISSUE TITLE
Allocator::pointer

### ISSUE THREAD

**Issue by thegreathir** [efficient/libcuckoo#111]
Why you stopped using Allocator::pointer?

https://github.com/efficient/libcuckoo/blob/86d5ef0da4fe52ba431704f374d1a7c79df99acb/libcuckoo/libcuckoo_bucket_container.hh#L45

In your last release you were using pointer which is provided by given allocator. This allows us to allocate a cuckoo hash map on shared memory using boost::interprocess::allocator.

https://github.com/efficient/libcuckoo/blob/8fc2d2eabd132004d9e88eb1b5663c8abf947acf/libcuckoo/cuckoohash_map.hh#L64

**Comment by thegreathir** [comment]
Hey?

**Comment by rayrapetyan** [comment]
@thegreathir, could you share your current implementation? How do you use libcuckoo in shared memory without code changes?

**Comment by thegreathir** [comment]
؟

**Comment by 363568233** [comment]
>Could you tell me  how to use libcuckoo（latest master code） in boost::interprocess ?  The code changed, It does not compile

**Comment by thegreathir** [comment]
https://github.com/efficient/libcuckoo/commit/86d5ef0da4fe52ba431704f374d1a7c79df99acb[](this commit) is patchable. The last release.

**Comment by rayrapetyan** [comment]
@thegreathir @manugoyal, there are two structures:
  using locks_t = std::vector<spinlock, rebind_alloc<spinlock>>;
  using all_locks_t = std::list<locks_t, rebind_alloc<locks_t>>;
which will not work with boost::interprocess::allocator and under a heavy load will either generate a deadlock or other racing issues, so  need to use some other containers here. I've used boost::interprocess::vector and boost::interprocess::list here instead in my naive implementation, but it's not portable.

**Comment by gatopeich** [comment]
> using all_locks_t = std::list<locks_t, rebind_alloc<locks_t>>;
> which will not work with `boost::interprocess::allocator`
Indeed, std::vector and std::list do not even compile for me with g++7
`/usr/include/c++/7/bits/stl_list.h:578:11: error: cannot convert ‘boost::interprocess::offset_ptr<std::_List_node<std::vector<cuckoohash_map...`
