### ISSUE TITLE
cuckoo as headers only

### ISSUE THREAD

**Issue by WilliamTambellini** [efficient/libcuckoo#112]
Hi
Would cuckoo be convertible to a headers only solution (no .c, no .cpp, no lib) ?
Congrats
Kind

**Comment by toojays** [comment]
It already is? You should be able to integrate it into a project using only the .hh files in the libcuckoo directory.

**Comment by WilliamTambellini** [comment]
Ok indeed, at least map can be used just by including the right header : example : 

add_executable(hellohash hellohash.cc)
target_include_directories(hellohash PRIVATE ${CMAKE_SOURCE_DIR})
target_compile_options(hellohash PUBLIC "-std=c++11")
# target_link_libraries(hellohash libcuckoo) # Not needed

That's a powerful feature perhaps worth it to be mentioned in the main md doc.
Tks

**Comment by manugoyal** [comment]
Yes I agree that this is worth highlighting! Added a commit (f3138045810b2c2e9b59dbede296b4a5194af4f9) which should hopefully make this feature a bit more prominent.
