### ISSUE TITLE
using cuckoohash_map with std::shared_ptr values

### ISSUE THREAD

**Issue by kurti77** [efficient/libcuckoo#114]
Hello,

I try to use cuckoohash_map with std::shared_ptr values:

class MyClass { // an expensive object irl
public:
	MyClass(std::string name, std::string path) : name_(name), path_(path) {};
	~MyClass() {};
private:
	std::string name_;
	std::string path_;
};

When I insert the objekt itself it works fine:

cuckoohash_map <int, MyClass> mytab;
b = mytab.insert(0, "name", "path");
MyClass my = mytab.find(0);

But when I naively try it with shared_ptr the compile (somewhat unsurprisingly) fails with the message 'std::shared_ptr<MyClass>::shared_ptr': no overloaded function takes 2 arguments:

cuckoohash_map <int, std::shared_ptr<class MyClass>> myptrtab;
b = myptrtab.insert(0, "name", "path");
std::shared_ptr<class MyClass> myptr = myptrtab.find(0);

Could you give my some help how to solve this?

**Comment by dnbaker** [comment]
`std::shared_ptr` isn't a type, it's a type template. You'd at least need to select the type `T` you want `shared_ptr<T>` to hold.

**Comment by kurti77** [comment]
Yes I'm sorry, I made a mistake when copying. It was meant to be:

cuckoohash_map <int, std::shared_ptr<MyClass>> myptrtab;
b = myptrtab.insert(0, "name", "path");
std::shared_ptr myptr = myptrtab.find(0);

**Comment by dnbaker** [comment]
I've been able to compile something like the following:
```
#include <string>
#include <memory>
#include "libcuckoo/cuckoohash_map.hh"

class MyClass { // an expensive object irl
public:
MyClass(std::string name, std::string path) : name_(name), path_(path) {};
~MyClass() {};
std::string to_string() const {
     return std::string("name: ") + name_ + "." + std::string("path: ") + path_ + ".";
}
private:
std::string name_;
std::string path_;
};

int main() {
    cuckoohash_map<int, std::shared_ptr<MyClass>> map;
    map.insert(1, std::make_shared<MyClass>("hello", "wurld"));
    map.insert(4, new MyClass("goodbye", "wurld"));
    auto ptr = map.find(1);
    std::fprintf(stderr, "ptr string value: %s\n", ptr->to_string().data());
    std::fprintf(stderr, "other ptr string value: %s\n", map.find(4)->to_string().data());
}

Daniels-MacBook-Pro:libcuckoo dnb$ ./zomg
ptr string value: name: hello.path: wurld.
other ptr string value: name: goodbye.path: wurld.
```

Your problem could be:

1. Not providing a template argument on `myptr` (it still needs to be `std::shared_ptr<MyClass>`).
2. Not providing a little help to the insert function. Because you're creating the shared_ptr, you might need a little more massaging to get it to compile. Note that I used `make_shared` and `new MyClass` to insert those values.

Does that help at all?

**Comment by kurti77** [comment]
I know I can insert a smart pointer if I create it beforehand.
I probably did not explain myself well: the thing is that this is an expensive object that I only want to create if it will be inserted (i.e. there is no object with the same key already in the map).
This is why I want to use the myptrtab.insert(0, "name", "path") syntax.

**Comment by jk-jeon** [comment]
I think what you want can be achieved by a proper use of `uprase_fn`?

**Comment by manugoyal** [comment]
Hi there, yes this is indeed a bit tricky. What we're lacking is some sort of iterator/accessor return type, which holds a lock on the returned element and lets you modify it after-the-fact. The best way to do this right now might be to use a custom wrapper type (just a sketch):

```
struct MyClassPtr {
  std::shared_ptr<MyClass> ptr;
  template <typename... Args>
  MyClassPtr(Args&&... args) : ptr(std::make_shared<MyClass>(std::forward<Args>(args)...) {}
};

cuckoohash_map<int, MyClassPtr> map;
map.insert(1, "hello", "world");
```
