### ISSUE TITLE
Issue in universal-benchmarks `--prefill` argument value detection

### ISSUE THREAD

**Issue by ivankochin** [efficient/libcuckoo#124]
Hi,
For example, when I try to run the following command:
` ./universal_benchmark --reads 60 --inserts 40 --initial-capacity 10 -–prefill 10`

I got following output in the console in `args` field:
`
...
"args": "--reads 60 --inserts 40 --erases 0 --updates 0 --upserts 0 --initial-capacity 10 --prefill 0 --total-ops 75 --num-threads 44 --seed 3203233284"
...
`

As you can see, the custom prefill value has been ignored.

If you change arguments order (swap `--initial-capacity` and `--prefill`), then the `--prefill` setting will be detected correctly.

**Comment by manugoyal** [comment]
Hi @ivankochin! I think the issue might be the characters in the `--prefill` argument in the command:
```
./universal_benchmark --reads 60 --inserts 40 --initial-capacity 10 -–prefill 10
```

It appears that the second `–` in `--prefill` is not an ASCII character. Here's what I printed:
```
Looking at argv -–prefill
strlen(argv) = 11
char 0 is 45
char 1 is -30
char 2 is -128
char 3 is -109
char 4 is 112
char 5 is 114
char 6 is 101
char 7 is 102
char 8 is 105
char 9 is 108
char 10 is 108
```

When I re-typed `--prefill` in my terminal, it seems to work.
