### ISSUE TITLE
Is it possible to publish a new release?

### ISSUE THREAD

**Issue by wang-luping** [efficient/libcuckoo#125]
Hi,

libcuckoo is awesome! I would like to adopt libcukoo as high-performance concurrent hash table in our project. However, I just notice the most-recent released version is v0.2, which were published three years ago. There are quite a lot of commits since then.

Is it possible to publish a new release of libcuckoo now? Or do you have a plan for providing newer release package? It would be nice to have a new version to include all newer changes and fixes. (PS: Our team requires a released version to be selected.)

Thanks.

**Comment by manugoyal** [comment]
Hi @wang-luping! Just updated the version to v0.3 and pushed a new tag. Hope this helps!

**Comment by wang-luping** [comment]
Great! Thank you for your help, I really appreciate it.
