### ISSUE TITLE
Tons of key-value pairs.

### ISSUE THREAD

**Issue by lxyscls** [efficient/libcuckoo#126]
Hello, I am looking for a hashtable which can hold millions or even more key-value pairs. Can this hashtable hold such payload, and give a good performance when there is some rebalance?

**Comment by xacrimon** [comment]
libcuckoo isn't the fastest thing in the world but it can grow large without issue.

**Comment by lxyscls** [comment]
@xacrimon Thanks for your reply.

I will use hashtable as a in-mem map for searching, and then do some disk opers. So I think the concurrency or speed is not the most important thing.
I will put millions of pairs into this map, so memory footprint, latency when resizing are what I need to pay more attention to.

**Comment by dave-andersen** [comment]
Libcuckoo can hold millions.  If you don't need concurrency, SwissTable is faster and is also reasonably memory efficient.
