### ISSUE TITLE
upsert reentrancy?

### ISSUE THREAD

**Issue by graehl** [efficient/libcuckoo#127]
Just a question:
if the constructor (or update fn) for a value causes another modification to the cuckoohash_map (say it's global), will corruption or deadlock ensue, or will the two or more insert/update both succeed?

**Comment by manugoyal** [comment]
Hey @graehl! Unfortunately we make no guarantees about mutating the hashtable within a callback or item constructor. The operation is performed under a non-reentrant spinlock, so if a hashtable operation called within the callback needs to access the same lock, it will never complete.

**Comment by graehl** [comment]
Thanks, I figured in absence of guarantee that was the case.
