### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by whatsthecraic** [efficient/libcuckoo#130]
Good afternoon,

how can an estimate be computed at run-time of the complete memory usage of the data structure?

Thanks

**Comment by manugoyal** [comment]
Hello! I can think of several options which might work:

1) libcuckoo is an allocator-aware container, so you could pass in an allocator which keeps track of memory usage, and query it at runtime. We actually utilize this approach for the libcuckoo [benchmark](https://github.com/efficient/libcuckoo/tree/master/tests/universal-benchmark) (option `-DUNIVERSAL_TRACKING_ALLOCATOR`). The code is [here](https://github.com/efficient/libcuckoo/blob/8785773896d74f72b6224e59d37f5f8c3c1e022a/tests/universal-benchmark/universal_table_wrapper.hh#L33).

2) There are some generic lunix tools for querying the memory usage of the entire program, such as `ps`, `pmap`, `valgrind`, etc. I'm not sure how much insight these tools can provide on the memory usage of the libcuckoo hashtable within your program, though.

**Comment by whatsthecraic** [comment]
oky, thanks!
