### ISSUE TITLE
remove supported?

### ISSUE THREAD

**Issue by ldalessa** [efficient/libcuckoo#33]
Is there an obvious way to synthesize an operation that inspects the state of the stored element and possibly erases it? My first thought would be that `update_fn` would return a bool to indicate that the entry should be removed as a side effect of the update...

The basic problem I'm trying to deal with is storing a manually reference counted record inside the table. When I decrement the reference count to 0 (via `update_fn` I would like to have the element removed).

**Comment by manugoyal** [comment]
It seems like the update_fn / upsert necessary functionality is pretty similar to the iterator functionality, so I'm thinking about a way to combine the two concepts. #32 asks for the same functionality for iterators.

**Comment by ldalessa** [comment]
Ah, I read that issue and didn't realize it was basically the same thing. Yes, we want an update_fn that can conditionally erase an element based on its data. Like I said, simply allowing the lambda to return a boolean would be ideal for us. (`uprase_fn`?)

**Comment by MRYingLEE** [comment]
Hi, I just made pull requests on find_fn and erase_fn. Also, I made examples.
I hope what I did is what you expected.

**Comment by manugoyal** [comment]
The tip of future-master should now provide this functionality through `erase_fn`.
