### ISSUE TITLE
Document: Please clarify the difference from STL's unordered_map.

### ISSUE THREAD

**Issue by MRYingLEE** [efficient/libcuckoo#34]
In the document, it was said that: "Its interface resembles that of STL's unordered_map but does contain some important differences.", but no detail was mentioned.

I am migrating some code from STL's unordered_map to libcucko's cuckoohash_map. Just in case I misunderstand something, can you clarify?

Thank you in advance,
Ying

**Comment by manugoyal** [comment]
Hi Ying,

You will most likely not be able to use `cuckoohash_map` as a drop-in replacement for `std::unordered_map`. We support effectively the same functionality as the STL map, but the available functions and their signatures differ quite a bit from the STL versions, as they are more tailored to a concurrent interface.

You should take a look at the Doxygen documentation, which is linked on the project's github page, and compare it to the STL documentation.
