### ISSUE TITLE
Will  it need lock for 2 threads doing insert and erase ?

### ISSUE THREAD

**Issue by Hedgezzz** [efficient/libcuckoo#49]
I have a  c++ application using libcuckoo library ,   there is a global var OrderRefMap like following

    cuckoohash_map<std::string, int, CityHasher<std::string>> OrderRefMap ;

one thread  do   OrderRefMap.insert  quite  fast , another thread do OrderRefMap.erase quite fast , too,
I think libcuckoo is high-performance concurrency hash library , means I should not worry  to use lock 
in inserting and erasing , so I just   code like : 

Thread1 :  
                  OrderRefMap.insert( s , 100 ) ;
Thread2 :   
                 OrderRefMap.erase( s ) ;

no need to  use lock like 

Thread1 :  
                  pthread_spin_lock(&orderspinlock) ;
                  OrderRefMap.insert( s , 100 ) ;
                 pthread_spin_unlock(&orderspinlock) ; 
Thread2 :   
                 pthread_spin_lock(&orderspinlock) ;
                 OrderRefMap.erase( s ) ;
                 pthread_spin_unlock(&orderspinlock) ;

Am I correct ?!

**Comment by mkaminsky** [comment]
Correct--the table itself does all of the locking that it needs.
