### ISSUE TITLE
Correctness improvements in future-master

### ISSUE THREAD

**Issue by rob-p** [efficient/libcuckoo#50]
I noticed this note in the README about `future-master`:

> This update also contains a number of small but important performance and correctness improvements.

Could you mention the correctness improvements?  What behavior in the existing master branch is not "correct"?

**Comment by manugoyal** [comment]
Maybe correctness wasn't the best word. As far as I remember, and looking through the commit history, there were no bugs in table correctness we fixed. More like small improvements, like better hashing, more `const`-correctness, etc. There was a small bug with the `LIBCUCKOO_DBG` function, but that doesn't impact the correctness of the table. I think I should just take out the correctness part, it's needlessly worrying.

Thanks for pointing this out!
