### ISSUE TITLE
move_to_bucket: destructors of relocated items are not called

### ISSUE THREAD

**Issue by nickhutchinson** [efficient/libcuckoo#52]
[`move_to_bucket()`](https://github.com/efficient/libcuckoo/blob/master/src/cuckoohash_map.hh#L265) looks to be called when performing cuckoo rehashing (`cuckoopath_move()`), and also during fast resize (`cuckoo_fast_double()`).

It moves elements from one slot to another, sets the first slot's `occupied_` bit to 0, but does not call the destructor on the moved-from element. This "don't call destructors" behaviour looks to be asserted in [test_resize.cc](https://github.com/efficient/libcuckoo/blob/master/tests/unit-tests/test_resize.cc#L57).

Do I have this right? If so, I think failing to call destructors is wrong and a resource leak -- e.g. consider a class that doesn't have a move constructor and gets copied instead.

**Comment by manugoyal** [comment]
Thanks for all the PR's! I just pushed a commit (5401c5e833ced8f369cbc9b0c6ecf03072e72ee9) which should fix this. I'll cherry pick it to master as well.
