### ISSUE TITLE
cacheint, spinlock instances not necessarily 64-byte aligned

### ISSUE THREAD

**Issue by nickhutchinson** [efficient/libcuckoo#53]
libcuckoo tags the definitions of the `cacheint` and `spinlock` classes with `alignas(64)`/`__attribute__((aligned(64)))`, presumably to avoid false sharing. However it goes on to use these classes in containers like `std::vector` and `lazy_array`. AFAIK the `std::vector` from libstdc++ or MSVC will not respect the alignment of its containing elements, and `lazy_array` doesn't seem to either. The `alignas` here ensures that elements are spaced 64-bytes apart, but doesn't ensure they're aligned on 64-byte boundaries.

You may want to consider writing a custom allocator that has support for over-aligned allocations and using it for these containers. The [`aligned_allocator_adaptor`](http://www.boost.org/doc/libs/1_61_0/boost/align/aligned_allocator_adaptor.hpp) from Boost gives an example.

**Comment by manugoyal** [comment]
Yes this is definitely an issue!

Now that the container is allocator-aware, I'm a bit reluctant to impose an aligned allocator on top of that, because if somebody does pass in an aligned-allocator, we'll be double-aligning each time. Also, I think this issue will be resolved in C++17, because new and delete will do over-aligned allocations properly.

Perhaps it's worth adding a warning to the documentation that the table makes use of over-aligned types so it's recommended to pass in an aligned allocator like the boost one.

**Comment by rayrapetyan** [comment]
I also observe a significant performance degradation (especially in simple tests) in a benchmark:
https://github.com/rayrapetyan/shmaps/blob/master/src/bench/libcuckoo.cpp

spinlock with alignas(64):
> -------------------------------------------------------------------------------------------------
> Benchmark                                                       Time             CPU   Iterations
> -------------------------------------------------------------------------------------------------
> LibCuckooFixture/BM_LibCuckoo_Set_IntInt                  5064304 ns      5044381 ns          134
> LibCuckooFixture/BM_LibCuckoo_SetGet_IntInt               6234558 ns      6216647 ns          116
> LibCuckooFixture/BM_LibCuckoo_Set_IntFooStats             5762053 ns      5751777 ns          112
> LibCuckooFixture/BM_LibCuckoo_SetGet_IntFooStats          7411218 ns      7406090 ns           89
> LibCuckooFixture/BM_LibCuckoo_Set_StringInt              22467459 ns     22423548 ns           31
> LibCuckooFixture/BM_LibCuckoo_SetGet_StringInt           32538412 ns     32516091 ns           22
> LibCuckooFixture/BM_LibCuckoo_Set_StringFooStatsExt      36773063 ns     36747684 ns           19
> LibCuckooFixture/BM_LibCuckoo_SetGet_StringFooStatsExt   46580592 ns     46559933 ns           15

spinlock without alignas(64):
> -------------------------------------------------------------------------------------------------
> Benchmark                                                       Time             CPU   Iterations
> -------------------------------------------------------------------------------------------------
> LibCuckooFixture/BM_LibCuckoo_Set_IntInt                  3566283 ns      3565072 ns          194
> LibCuckooFixture/BM_LibCuckoo_SetGet_IntInt               5410120 ns      5278531 ns          147
> LibCuckooFixture/BM_LibCuckoo_Set_IntFooStats             3915558 ns      3906744 ns          160
> LibCuckooFixture/BM_LibCuckoo_SetGet_IntFooStats          5430732 ns      5429336 ns          131
> LibCuckooFixture/BM_LibCuckoo_Set_StringInt              18859071 ns     18838237 ns           38
> LibCuckooFixture/BM_LibCuckoo_SetGet_StringInt           27735135 ns     27696308 ns           26
> LibCuckooFixture/BM_LibCuckoo_Set_StringFooStatsExt      34524203 ns     34514150 ns           20
> LibCuckooFixture/BM_LibCuckoo_SetGet_StringFooStatsExt   47511294 ns     47508333 ns           15
