### ISSUE TITLE
libcuckoo should not pollute global namespace

### ISSUE THREAD

**Issue by nickhutchinson** [efficient/libcuckoo#54]
Portions of libcuckoo pollute the global namespace with un-namespaced symbols, e.g. `lazy_array`, `DEFAULT_SIZE`. These symbols should either be namespaced or prefixed with 'libcuckoo_' or similar.

**Comment by manugoyal** [comment]
Thanks! Fixed in (f9c1d7eb4dcd1bca80116d07c95c822bdd5a127b).
