### ISSUE TITLE
setKV contains static object with an exit-time destructor

### ISSUE THREAD

**Issue by nickhutchinson** [efficient/libcuckoo#55]
[`setKV()`](https://github.com/efficient/libcuckoo/blob/master/src/cuckoohash_map.hh#L242) declares a `static allocator_type` variable which may have an exit-time destructor. With appropriate warning settings, Clang will warn you about these, and in a codebase I work on they are a compile error because they're seen as dangerous.

Given that libcuckoo doesn't currently support stateful C++11 allocators anyway, I think you should be able to simply drop the `static` keyword here.

**Comment by manugoyal** [comment]
Decided to support passing in a custom allocator in (8ed01cd73ae0abfec754296c300fdbf547c57ec7). This should fix the problem, too. Thanks!

**Comment by nickhutchinson** [comment]
Thanks!
