### ISSUE TITLE
Delete value from input variable after upsert or insert

### ISSUE THREAD

**Issue by krsvital** [efficient/libcuckoo#60]
I havent use one variable many times becouse it swaped with other varible with null value

example:

typedef cuckoohash_map<std::string,std::string> s_table;
s_table s_sessions;
s_table s_services;

auto updatefn = [](std::string &a){};

std::string *str = new std::string("123");
auto res = s_sessions.upsert(*str, updatefn, cid);
if(!res){

}
else{
// problem here!!! 
// *str after upsert or insert swap with other varidable that have null value and string below is
// "STRING: ", but it has to be "STRING: 123"
    std::cout << "STRING: " << *str << std::endl;

   s_services.insert(*str, 0); // this not working becouse after upsert *str is empty
}

**Comment by manugoyal** [comment]
Originally, the specification of `upsert` dictated that the key you pass in will be move-constructed, regardless of whether or not the upsert succeeds, which would explain the behavior you're observing. But after you pointed this out, I took a closer look and realized this restriction is not necessary, and modified the code to only move the key if the insert will succeed.

So with the latest commit (9d563aee02a5cef8322ac5e0abbd7f4fd687b292), your code should behave the way you expect.

**Comment by krsvital** [comment]
thanks, it works well!
