### ISSUE TITLE
How to pass multiple values to update_fn in upsert

### ISSUE THREAD

**Issue by domino-succ** [efficient/libcuckoo#61]
It looks like current `upsert` only passes one parameters to `update_fn`, and this parameter is the value of the corresponding key in the hash table, like : `upsert(key, upsert_fn, cur_num)`; If I wanna pass `cur_num `to `upsert_fn`, how can I do that ?

**Comment by rob-p** [comment]
Why not just have `upsert_fn` be a lambda and bind the variable?  For example:

```
int cur_num = 5;
auto upserter = [&cur_num] (Key_T& key) -> void {
  cur_num += 1;
  // do other insertion stuff here
};

map.upsert_fn(the_key, upserter);
```

**Comment by domino-succ** [comment]
Good idea. Thanks!

**Comment by dnbh** [comment]
Might this hint be worth providing in the documentation for future reference?

**Comment by manugoyal** [comment]
Yup, updated the docs.
