### ISSUE TITLE
How to efficiently update and delete a record? 

### ISSUE THREAD

**Issue by Michael-Tieying-Zhang** [efficient/libcuckoo#64]
The table is like this : `<string, int> `. There is function `foo` that lookups the table with a `key`. If there is a record matching the `key`, `foo` decrease the value by `1`. If the value  is `0`, `foo` delete the record. 

I see there is a `update_fn(key, fn)` where `fn` can be defined to update the value. But how can I delete the record using `fn` ?

**Comment by manugoyal** [comment]
`erase_fn` is probably what you need (http://efficient.github.io/libcuckoo/classcuckoohash__map.html#a7c454c5fcdf11a59a576c0602be1a6b4)

**Comment by Michael-Tieying-Zhang** [comment]
@manugoyal Thanks
