### ISSUE TITLE
Using string as the key

### ISSUE THREAD

**Issue by Michael-Tieying-Zhang** [efficient/libcuckoo#65]
Is it ok (fast) to use string as the key ? or I need to use integer and manually hash the string to integer.

**Comment by manugoyal** [comment]
Should be just as fast. Comparisons are done first by an integer partial hash, then only by string on a match, so there's a high probability that only one string comparison is done per find/insert/update/etc.

**Comment by Michael-Tieying-Zhang** [comment]
@manugoyal Thanks
