### ISSUE TITLE
Complex transaction support?

### ISSUE THREAD

**Issue by ldalessa** [efficient/libcuckoo#71]
I have a use case where I am using a table to rendezvous producer/consumer relationships through keys, where either the producer or the consumer(s) may arrive first. 

The basic functionality on the single producer side is satisfied by the `upsert` functionality, however I have this consumer logic that is basically:

  * If a record does not exist then insert a new record.
  * If a record exists then decrement the number of consumers.
  * If I am the last expected consumer of this record then erase the record.

I can't figure out a way to do this in one transaction, as the `erase_fn` won't insert a new record, and the `upsert` won't erase a record. I can support this functionality with 2 operations and a lambda. I'd obviously like to avoid this extra synchronization...

Is there an existing option that I could leverage to do this as a single call?

Luke

**Comment by manugoyal** [comment]
I see. I guess we really do need to add an uprase_fn, which behaves like upsert, but gives you the erase_fn interface when you want to do an update. I'll let you know when that's available.

**Comment by rayrapetyan** [comment]
Would calling erase from an update_fn produce a potential deadlock?

**Comment by manugoyal** [comment]
Hey! Sorry this took forever. I just added `uprase_fn` in this commit: 7963f9b71d5fbdb7d2d949de72060461c4941676

@rayrapetyan I think @ldalessa is looking to do this in a single transaction, with no possibility of races with other threads. Splitting this up into multiple operations leaves room for other threads to interfere with the operation.
