### ISSUE TITLE
`upsert` not returning bool

### ISSUE THREAD

**Issue by ldalessa** [efficient/libcuckoo#73]
I'm having a weird problem with `upsert`. It's likely a user error, but I can't seem to figure it out. My compiler seems to think that it has a void return value.

```C++
bool test() {
  cuckoohash_map<int, int> test;
  test.upsert(1, [](int& i) { i = 1; });
  return test.upsert(1, [](int& i) { i = 1; });
}
```

```bash
test.cpp:  error: void value not ignored as it ought to be
   return test.upsert(1, [](int& i) { i = 1; });
                                              ^
```

Is there something obvious that I'm doing wrong? This is with gcc 5.3.0.

**Comment by manugoyal** [comment]
Huh that's weird. It works for me on clang, and g++ 6.3. Can you verify if this error pops up on other compiler versions?

**Comment by ldalessa** [comment]
Figure this out. Complete user error... somehow I was getting a very old libcuckoo header instead of the one I wanted. Sorry for the noise.
