### ISSUE TITLE
Doubt with the update rule in upsert function

### ISSUE THREAD

**Issue by k3yavi** [efficient/libcuckoo#79]
Hi, check the following piece of code from [here](https://github.com/COMBINE-lab/salmon/blob/master/include/EquivalenceClassBuilder.hpp#L83).

```
struct TGValue {
std::atomic<uint64_t> count{0};
};

auto upfn = [](TGValue& x) -> void {
    // update the count
    x.count++;
};

TGValue v(1);
<cuckoo_object>.upsert(<key_object>, upfn, v);
```

My confusion is do I have to define the count variable as `atomic` type or a normal int would do, if I want to get the correct count for the frequency of the upsert function call.
Basically, if the order of the upsert function call doesn't matter to me then does the <cuckoo_object>.upsert function serialize the update/*initialization*(you can imagine two initialization call concurrently) call to avoid race condition inside the `TGValue` object? It's not very clear from the documentation.

**Comment by manugoyal** [comment]
Yes. Access to all data inside the table is serialized, as each item is protected by a mutex. So a normal int should suffice.

**Comment by k3yavi** [comment]
Thanks @manugoyal !
