### ISSUE TITLE
Cannot install libcuckoo library

### ISSUE THREAD

**Issue by hungptit** [efficient/libcuckoo#83]
I cannot install libcuckoo because libcuckoo_lock_array.hh is removed from the master branch. Please see my patch below. Thanks.

---
 libcuckoo/CMakeLists.txt | 1 -
 1 file changed, 1 deletion(-)

diff --git a/libcuckoo/CMakeLists.txt b/libcuckoo/CMakeLists.txt
index ec8e3b0..9147856 100644
--- a/libcuckoo/CMakeLists.txt
+++ b/libcuckoo/CMakeLists.txt
@@ -23,7 +23,6 @@ FILES
     cuckoohash_config.hh
     cuckoohash_map.hh
     cuckoohash_util.hh
-    libcuckoo_lock_array.hh
     libcuckoo_bucket_container.hh
 DESTINATION
     ${CMAKE_INSTALL_PREFIX}/include/libcuckoo
-- 
2.13.0

**Comment by manugoyal** [comment]
Thanks for pointing this out @hungptit! Should be fixed now.
