### ISSUE TITLE
Add a gdb pretty printer.

### ISSUE THREAD

**Issue by toojays** [efficient/libcuckoo#85]
I'm looking at a core file right now where I'd really like to be able to dump out the content of my cuckoohash table. If we had a gdb pretty printer, that would be awesome.

**Comment by manugoyal** [comment]
Yup this is a good idea. I'll work on adding one, seems pretty straightforward.

**Comment by manugoyal-nuro** [comment]
682118b37bfd38e1dd58784ca2263206a0c49a6a adds a pretty-printer.

**Comment by manugoyal** [comment]
Commit 682118b37bfd38e1dd58784ca2263206a0c49a6a adds a pretty-printer.
