### ISSUE TITLE
proper way to delete while iterating

### ISSUE THREAD

**Issue by isaacyho** [efficient/libcuckoo#89]
say i loop through a locked table as follows:

```
    auto lt = counts_hash.lock_table();
    for (const auto &it : lt) {
        counts_hash.erase(it.first); 
      }
    }
```

Does the above iterate correctly after deletion?  If not, what is the correct/efficient way to do this? (the stl pattern is not supported here)  Note that this thread is the only one with a lock. My code appears to be hanging here.

I know there is a closed thread https://github.com/efficient/libcuckoo/issues/32

But there are two locks in that case.

**Comment by manugoyal** [comment]
Hi @isaacyho. If you're locking the table, you can actually erase elements through the `locked_table` object, which supports the exact same interface as `std::unordered_map`. So you could do something like this:
```
auto lt = counts_hash.lock_table();
auto lt_it = lt.begin();
while (lt_it != lt.end()) {
  lt_it = lt.erase(lt_it);
}
```
