### ISSUE TITLE
Please add protection against include of .h files multiple times

### ISSUE THREAD

**Issue by pavel-odintsov** [efficient/libcuckoo#9]
Hello!

I tried to include it multiple times and got a lot of errors.

Please add protections, it implemented with:
```C
#ifndef _FAST_LIBRARY_H
#define _FAST_LIBRARY_H

#endif 
```

**Comment by manugoyal** [comment]
Hi Pavel,

Looks like we forgot to add one for city_hasher, but the rest had include guards. The latest master should have updated include guards, does it work for you?

-Manu
